runtime: java17
env: flex

env_variables:
  SPRING_PROFILES_ACTIVE: prod
  DATABASE_URL: ${DATABASE_URL}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  MAIL_HOST: ${MAIL_HOST}
  MAIL_PORT: ${MAIL_PORT}
  MAIL_USERNAME: ${MAIL_USERNAME}
  MAIL_PASSWORD: ${MAIL_PASSWORD}
  APP_EMAIL_FROM: ${APP_EMAIL_FROM}
  APP_URL: ${APP_URL}

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 