[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar target/dump-truck-services-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/ping"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
SPRING_PROFILES_ACTIVE = "railway"
PORT = "8080" 