services:
  - type: web
    name: dump-truck-services
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/dump-truck-services-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: MAIL_HOST
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: APP_EMAIL_FROM
        sync: false
      - key: APP_VERIFICATION_URL
        sync: false 